site_name: Memory &omega;
site_url: https://www.doubleu.codes/docs/
site_description: Documentation
site_author: W Anders
repo_url: https://github.com/wranders/docs/
edit_uri: edit/src/docs
copyright: 'Copyright &copy; 2018-2020 W Anders'
remote_branch: master

theme:
  name: material
  language: en
  palette:
    primary: 'green'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'img/logo.png'
  favicon: 'img/favicon.ico'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true

nav:
  - Welcome: 'README.md'
  - Knowledge Base:
    - 'kb/README.md'
    - IETF RFC:
      - LDAP: 'rfc/ldap/README.md'
    - Servers:
      - Dell R510: 'kb/servers/dell-r510/README.md'
      - Dell R610: 'kb/servers/dell-r610/README.md'
    - Interface Bit Rates: 'kb/interface-bit-rates/README.md'
  - Guides:
    - 'guides/README.md'
    - Services:
      - 'guides/services/README.md'
      - Xen-Orchestra: 'guides/services/xen-orchestra/README.md'
    - Self-Signed Certificate with Root: 'guides/self-signed-certificate-with-root/README.md'