# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Memory &omega;
site_url: https://docs.doubleu.codes/
site_description: Documentation
site_author: W Anders
repo_name: wranders/docs
repo_url: https://github.com/wranders/docs/
edit_uri: edit/master/docs
copyright: 'Copyright &copy; 2018-2022 W Anders'

theme:
  favicon: 'img/favicon.ico'
  features:
  - header.autohide
  - navigation.indexes
  - navigation.instant
  - navigation.tabs
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.integrate
  font: false
  icon:
    repo: fontawesome/brands/github
  language: en
  logo: 'img/logo.png'
  name: material
  palette:
  - scheme: default
    media: "(prefers-color-scheme: light)"
    primary: 'green'
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    media: "(prefers-color-scheme: dark)"
    primary: 'green'
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

extra_css:
- stylesheets/hideFooterNav.css

markdown_extensions:
- admonition
- attr_list
- footnotes
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- tables
- toc:
    permalink: true

plugins:
- git-revision-date-localized:
    enable_creation_date: true
- search

nav:
- Welcome: 'README.md'
- Knowledge Base:
  - 'kb/README.md'
  - CoreOS:
    - 'kb/coreos/README.md'
    - sshd Policy: 'kb/coreos/sshd-policy/README.md'
  - IETF RFC:
    - 'kb/ietf-rfc/README.md'
    - LDAP: 'kb/ietf-rfc/ldap/README.md'
  - Servers:
    - 'kb/servers/README.md'
    - Dell R510: 'kb/servers/dell-r510/README.md'
    - Dell R610: 'kb/servers/dell-r610/README.md'
  - Interface Bit Rates: 'kb/interface-bit-rates/README.md'
  - OpenSSL Database Format: 'kb/openssl-database-format/README.md'
  - Package-Buddy QR Code: 'kb/packagebuddy-qr-code/README.md'
- Guides:
  - 'guides/README.md'
  - WSL:
    - 'guides/wsl/README.md'
    - Automatic Hosts File: 'guides/wsl/automatic-hosts-file/README.md'
  - XCP-ng:
    - 'guides/xcp-ng/README.md'
    - ZFS Local Storage: 'guides/xcp-ng/zfs-local-storage/README.md'
  - Kickstart Install: 'guides/kickstart-install/README.md'
  - Self-Signed Certificate with Root: 'guides/self-signed-certificate-with-root/README.md'
  - OpenSSL Request ADCS: 'guides/openssl-req-adcs/README.md'
- Lab:
  - 'lab/README.md'
  - 'Root CA': 'lab/root-ca/README.md'