site_name: Public Docs
site_url: https://www.doubleu.codes/pubdocs/
site_description: Public Documentation
site_author: W Anders
repo_url: https://github.com/wranders/pubdocs/
edit_uri: edit/src/docs
copyright: 'Copyright &copy; 2019 W Anders'
remote_branch: master

theme:
  name: material
  language: en
  palette:
    primary: 'green'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'img/logo.png'
  favicon: 'img/favicon.ico'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true

nav:
  - Welcome: 'README.md'
  - Knowledge Base:
    - 'kb/README.md'
    - Servers:
      - Dell R510: 'kb/servers/dell-r510/README.md'
      - Dell R610: 'kb/servers/dell-r610/README.md'
    - Interface Bit Rates: 'kb/interface-bit-rates/README.md'
    - IETF RFC:
      - LDAP: 'rfc/ldap/README.md'
  - Guides:
    - Services:
#     - Gitea:
#       - Gitea - CentOS: 'guides/services/gitea/centos/README.md'
      - Xen Orchestra:
        - Xen Orchestra - CentOS 7: 'guides/services/xen-orchestra/centos7/README.md'
