# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: build
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: |
        mkdocs --version
        mkdocs build
    - uses: actions/upload-pages-artifact@v1
      with:
        path: site/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: deployment
      uses: actions/deploy-pages@v1
